### ISSUE TITLE
Dashboard Graph API

### ISSUE THREAD

**Issue by nadeemkhedr** [x-team/resource-dashboard-server#13]
### Implementation Details

`x axis` will show 12 months, today's month will be the 4th month in the axis, the 3 before it are the 3 previous months & everything after it are the following months

------

For each month (lets call it `currentMonth` for referring bellow) we need to calculate the graph fields, the following is the calculation logic for each field

**Available**
All `developers` that has `available` equal `true` **or** `availableDate` less than or equal `currentMonth`

**Booked**
All `developers` that has `available` equal `false` **and** `availableDate` more than `currentMonth`

**Needed**
All `opportunities` that `currentMonth` is between `dateFrom` & `dateTo`

**Comment by kamilogorek** [comment]
This solution is very error prone imo, as we can't predict future changes. One of the solutions here would be to create daily/hourly snapshots of state and use it as a graph data source.
In addition to that I believe we shouldn't display graph for future months and even days.
Instead we should display up to 12 months from the past (including current one) and eventually allow user to switch into "day mode" which will display every snapshot from the beginning of the month (we can include month picker as well here).
